PREFIX edge:   <http://tinkerpop.com/pgm/edge/>
PREFIX vertex: <http://tinkerpop.com/pgm/vertex/>
PREFIX prop:   <http://tinkerpop.com/pgm/property/>
PREFIX pgm:    <http://tinkerpop.com/pgm/ontology#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# Select all the userProfile nodes and their name properties...
SELECT ?id ?u WHERE {
   ?u a pgm:Vertex ;
      prop:__type  "UserProfile" ;
      prop:__id     ?id .
}

ORDER BY ?id
LIMIT 100
