#!/bin/sh
# Load an EAD file

ARGS="$@"

mvn  -Dexec.classpathScope=compile \
    -quiet \
    -pl ehri-cmdline \
    -Dexec.mainClass="eu.ehri.project.commands.CmdEntryPoint" \
    -Dlog4j.rootLogger=WARN \
    -Dexec.args="$ARGS" \
    exec:java
