#!/bin/bash

# Get the current dir...
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Source the libs (for classpath building etc)
. $DIR/lib.sh

checkenv
buildclasspath

java -Xmx1g -cp "$CLASSPATH" eu.ehri.project.commands.CmdEntryPoint $NEO4J_DB "$@"



